# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
os:
  - linux
  - osx

osx_image: xcode10.1

after_success:
  - Rscript -e 'covr::codecov()'
