---
title: "Getting started with regDIF"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This vignette introduces regDIF to the general user by providing common use cases.

## LASSO regularization for evaluating DIF in 2PL-IRT model, large lambda parameter --> no DIF effects
```{r,eval=T,message=F,echo=F}
library(regDIF)
head(ida)
x <- ida[,7:9]
y <- ida[,1:6]
fit <- regDIF(x, y, family = "bernoulli", penalty = "lasso", lambda = 2)
summary(fit)
```

## LASSO regularization for evaluating DIF in CFA model
```{r,eval=T,message=F,echo=F}
# library(lavaan)
# school_predictor <- HolzingerSwineford1939[,c("school")]
# speed_responses <- HolzingerSwineford1939[,c("x7","x8","x9")]
# holzswine_model <- 'speed =~ NA*x7 + c(a,a)*x8 + x9
#                     speed ~~ c(1,NA)*speed
#                     x8 ~ c(b,b)*1
#                     speed ~ c(0,NA)*1'
# fit_holzswine_lavaan <- cfa(model = holzswine_model, data = HolzingerSwineford1939, group = "school")
# fit_holzswine_regDIF <- regDIF(school_predictor, speed_responses, family = "gaussian", penalty = "lasso", lambda = 0, anchor = 2, standardize = F, quadpts = 101)
# summary(fit_holzswine_lavaan)
# summary(fit_holzswine_regDIF)
```

