# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bernoulli_traceline4 <- function(p_item, theta, predictors, samp_size, num_quadpts) {
    .Call(`_regDIF_bernoulli_traceline4`, p_item, theta, predictors, samp_size, num_quadpts)
}

estep <- function(p, theta, responses, predictors, samp_size, num_items, num_responses, num_quadpts) {
    .Call(`_regDIF_estep`, p, theta, responses, predictors, samp_size, num_items, num_responses, num_quadpts)
}

bernoulli_traceline <- function(p_c0, p_a0, p_c1, p_a1, theta, predictors, samp_size, num_quadpts) {
    .Call(`_regDIF_bernoulli_traceline`, p_c0, p_a0, p_c1, p_a1, theta, predictors, samp_size, num_quadpts)
}

categorical_traceline <- function(p_c0, p_a0, p_thr, p_c1, p_a1, theta, predictors, samp_size, num_quadpts, num_responses_item) {
    .Call(`_regDIF_categorical_traceline`, p_c0, p_a0, p_thr, p_c1, p_a1, theta, predictors, samp_size, num_quadpts, num_responses_item)
}

cumulative_traceline <- function(p_c0, p_a0, p_thr, p_c1, p_a1, theta, predictors, samp_size, num_quadpts, num_responses_item) {
    .Call(`_regDIF_cumulative_traceline`, p_c0, p_a0, p_thr, p_c1, p_a1, theta, predictors, samp_size, num_quadpts, num_responses_item)
}

bernoulli_traceline2 <- function(p_item, theta, predictors, samp_size, num_quadpts, num_items) {
    .Call(`_regDIF_bernoulli_traceline2`, p_item, theta, predictors, samp_size, num_quadpts, num_items)
}

bernoulli_traceline3 <- function(p_item, theta, predictors, samp_size, num_quadpts) {
    .Call(`_regDIF_bernoulli_traceline3`, p_item, theta, predictors, samp_size, num_quadpts)
}

