# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_thresh_est <- function(z, alpha, tau) {
    .Call(`_regDIF_soft_thresh_est`, z, alpha, tau)
}

firm_thresh_est <- function(z, alpha, tau, gamma) {
    .Call(`_regDIF_firm_thresh_est`, z, alpha, tau, gamma)
}

dnormCpp <- function(theta, alpha_impact, phi_impact, num_quadpts) {
    .Call(`_regDIF_dnormCpp`, theta, alpha_impact, phi_impact, num_quadpts)
}

bernoulli_traceline_est <- function(p_item, theta, predictors, samp_size, num_quadpts) {
    .Call(`_regDIF_bernoulli_traceline_est`, p_item, theta, predictors, samp_size, num_quadpts)
}

bernoulli_traceline_cpp <- function(p_item, theta, predictors, samp_size, num_quadpts) {
    .Call(`_regDIF_bernoulli_traceline_cpp`, p_item, theta, predictors, samp_size, num_quadpts)
}

d_alpha_est <- function(p_alpha, p_phi, etable_all, theta, mean_predictors, var_predictors, cov, samp_size, num_items, num_quadpts) {
    .Call(`_regDIF_d_alpha_est`, p_alpha, p_phi, etable_all, theta, mean_predictors, var_predictors, cov, samp_size, num_items, num_quadpts)
}

d_phi_est <- function(p_alpha, p_phi, etable_all, theta, mean_predictors, var_predictors, cov, samp_size, num_items, num_quadpts) {
    .Call(`_regDIF_d_phi_est`, p_alpha, p_phi, etable_all, theta, mean_predictors, var_predictors, cov, samp_size, num_items, num_quadpts)
}

d_bernoulli_est <- function(parm, p_item, etable1, etable2, theta, predictors, cov, samp_size, num_items, num_quadpts) {
    .Call(`_regDIF_d_bernoulli_est`, parm, p_item, etable1, etable2, theta, predictors, cov, samp_size, num_items, num_quadpts)
}

em_step2 <- function(p, theta, responses, predictors, mean_predictors, var_predictors, samp_size, num_items, num_responses, num_quadpts) {
    .Call(`_regDIF_em_step2`, p, theta, responses, predictors, mean_predictors, var_predictors, samp_size, num_items, num_responses, num_quadpts)
}

em_step <- function(p, theta, responses, predictors, mean_predictors, var_predictors, itemtypes, penalty, tau, pen, alpha, gamma, anchor, rasch, samp_size, num_items, num_responses, num_quadpts, num_predictors) {
    .Call(`_regDIF_em_step`, p, theta, responses, predictors, mean_predictors, var_predictors, itemtypes, penalty, tau, pen, alpha, gamma, anchor, rasch, samp_size, num_items, num_responses, num_quadpts, num_predictors)
}

