# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_thresh_est <- function(z, alpha, tau) {
    .Call(`_regDIF_soft_thresh_est`, z, alpha, tau)
}

firm_thresh_est <- function(z, alpha, tau, gamma) {
    .Call(`_regDIF_firm_thresh_est`, z, alpha, tau, gamma)
}

dnormCpp <- function(theta, alpha_impact, phi_impact, num_quadpts) {
    .Call(`_regDIF_dnormCpp`, theta, alpha_impact, phi_impact, num_quadpts)
}

bernoulli_traceline_deriv <- function(p_item, theta, predictors, samp_size, num_quadpts) {
    .Call(`_regDIF_bernoulli_traceline_deriv`, p_item, theta, predictors, samp_size, num_quadpts)
}

bernoulli_traceline_cpp <- function(p_item, theta, predictors, samp_size, num_quadpts) {
    .Call(`_regDIF_bernoulli_traceline_cpp`, p_item, theta, predictors, samp_size, num_quadpts)
}

categorical_traceline_cpp <- function(p_item, theta, predictors, samp_size, num_responses_item, num_quadpts) {
    .Call(`_regDIF_categorical_traceline_cpp`, p_item, theta, predictors, samp_size, num_responses_item, num_quadpts)
}

cumulative_traceline_cpp <- function(p_item, theta, predictors, samp_size, num_responses_item, num_quadpts) {
    .Call(`_regDIF_cumulative_traceline_cpp`, p_item, theta, predictors, samp_size, num_responses_item, num_quadpts)
}

d_alpha_cpp <- function(p_alpha, p_phi, etable_all, theta, mean_predictors, var_predictors, cov, samp_size, num_items, num_quadpts) {
    .Call(`_regDIF_d_alpha_cpp`, p_alpha, p_phi, etable_all, theta, mean_predictors, var_predictors, cov, samp_size, num_items, num_quadpts)
}

d_phi_cpp <- function(p_alpha, p_phi, etable_all, theta, mean_predictors, var_predictors, cov, samp_size, num_items, num_quadpts) {
    .Call(`_regDIF_d_phi_cpp`, p_alpha, p_phi, etable_all, theta, mean_predictors, var_predictors, cov, samp_size, num_items, num_quadpts)
}

d_bernoulli_cpp <- function(parm, p_item, etable1, etable2, theta, predictors, cov, samp_size, num_items, num_quadpts) {
    .Call(`_regDIF_d_bernoulli_cpp`, parm, p_item, etable1, etable2, theta, predictors, cov, samp_size, num_items, num_quadpts)
}

d_categorical_cpp <- function(parm, p_item, etable, theta, predictors, thr, cov, samp_size, num_responses_item, num_items, num_quadpts) {
    .Call(`_regDIF_d_categorical_cpp`, parm, p_item, etable, theta, predictors, thr, cov, samp_size, num_responses_item, num_items, num_quadpts)
}

